version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
