apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerproject-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerproject
  template:
    metadata:
      labels:
        app: dockerproject
    spec:
      containers:
        - name: dockerproject
          image: <DOCKERHUB_USER>/dockerproject:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/ecommerce"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
